stages:
  - build
  - deploy
#    - test

variables:
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

  # build breaks with
  # docker: Cannot connect to the Docker daemon at tcp://docker:2375. Is the docker daemon running?.
  # see https://gitlab.com/gitlab-org/gitlab-runner/issues/4501 for details
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.1-dind

before_script:
  - "cd backend"

build:
  image: docker:stable
  stage: build
  when: manual
  tags:
    - h1lscapet01.mhx.local
  script:
    - "docker build -t landscape_registry_backend -f ./LandscapeRegistry/Dockerfile ."

test-deploy:
  image: docker-registry.mhx.at/infra-docker/builddeploy-php:7.2.1
  stage: deploy
  environment: mhx-test
  when: manual
  tags:
    - h1lscapet01.mhx.local
  script:
    # deploy
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - ssh cicdauto@10.131.1.13 hostname




#test:
#    stage: test
#    script: 
#        - "cd $test"
#        - "dotnet test"
