stages:
 - build
 - publish

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"



build-backend:
  image: docker:stable
  stage: build
  when: on_success
  tags:
    - dockerbuild
  services:
    - docker:19.03.1-dind
  only: 
    - tags
  before_script:
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  script:
    - "cd backend"
    - "VERSION=$CI_COMMIT_TAG"
    - echo "Building backend version $VERSION"
    - "docker build -t $CI_REGISTRY/landscape/omnikeeper/backend:$VERSION -t $CI_REGISTRY/landscape/omnikeeper/backend:latest -f ./Omnikeeper/Dockerfile --build-arg version=$VERSION ."
    - "docker push $CI_REGISTRY/landscape/omnikeeper/backend"


build-frontend:
  image: docker:stable
  stage: build
  when: on_success
  tags:
    - dockerbuild
  services:
    - docker:19.03.1-dind
  only: 
    - tags
  before_script:
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
  script:
    - "cd frontend"
    - "VERSION=$CI_COMMIT_TAG"
    - echo "Building frontend version $VERSION"
    - "docker build -t $CI_REGISTRY/landscape/omnikeeper/frontend:$VERSION -t $CI_REGISTRY/landscape/omnikeeper/frontend:latest --build-arg version=$VERSION ."
    - "docker push $CI_REGISTRY/landscape/omnikeeper/frontend"
    

build-nuget-package-base:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
  stage: build
  when: on_success
  tags:
    - dockerbuild
  services:
    - docker:19.03.1-dind
  only: 
    - tags
  script:
    - "VERSION=$CI_COMMIT_TAG"
    - echo "Building nuget package for omnikeeper base version $VERSION"
    - "dotnet pack backend/Omnikeeper.Base/Omnikeeper.Base.csproj /p:Version=${VERSION} -c Release"
    - "mv backend/Omnikeeper.Base/bin/Release/Omnikeeper.Base.${VERSION}.nupkg Omnikeeper.Base.nupkg"
  artifacts:
    paths:
      - Omnikeeper.Base.nupkg
    expire_in: 2 days
publish-nuget-package-base:
  image: docker-registry.mhx.at/infra-docker/container-images/push-to-nexus-nuget:latest
  stage: publish
  when: on_success
  needs: ["build-nuget-package-base"]
  variables:
    NEXUS_BASEURL: "https://repo.mhx.at"
    PACKAGE_NAME: "Omnikeeper.Base"
  script:
    - sh /upload-nuget.sh Omnikeeper.Base.nupkg
  only: 
    - tags

build-nuget-package-okplugin-active-directory-xml-ingest:
  image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
  stage: build
  when: on_success
  tags:
    - dockerbuild
  services:
    - docker:19.03.1-dind
  only: 
    - tags
  script:
    - "VERSION=$CI_COMMIT_TAG"
    - echo "Building nuget package for omnikeeper plugin ActiveDirectoryXMLIngest $VERSION"
    - "dotnet pack backend/OKPluginActiveDirectoryXMLIngest/OKPluginActiveDirectoryXMLIngest.csproj /p:Version=${VERSION} -c Release"
    - "mv backend/OKPluginActiveDirectoryXMLIngest/bin/Release/OKPluginActiveDirectoryXMLIngest.${VERSION}.nupkg OKPluginActiveDirectoryXMLIngest.nupkg"
  artifacts:
    paths:
      - OKPluginActiveDirectoryXMLIngest.nupkg
    expire_in: 2 days
publish-nuget-package-okplugin-active-directory-xml-ingest:
  image: docker-registry.mhx.at/infra-docker/container-images/push-to-nexus-nuget:latest
  stage: publish
  when: on_success
  needs: ["build-nuget-package-okplugin-active-directory-xml-ingest"]
  variables:
    NEXUS_BASEURL: "https://repo.mhx.at"
    PACKAGE_NAME: "OKPluginActiveDirectoryXMLIngest"
  script:
    - sh /upload-nuget.sh OKPluginActiveDirectoryXMLIngest.nupkg
  only: 
    - tags