image: docker:latest

services:
  - docker:dind


stages:
    - build
#    - test

#variables:
#    test: "Example.Test"

before_script:
    - "cd backend"

build:
    stage: build
    tags:
        - h1lscapet01.mhx.local
    script:
        - "docker build -t landscape_registry_backend -f ./LandscapeRegistry/Dockerfile ."

#test:
#    stage: test
#    script: 
#        - "cd $test"
#        - "dotnet test"