image: mcr.microsoft.com/dotnet/core/aspnet:3.1

stages:
    - build
    - test

variables:
    test: "Example.Test"

before_script:
    - "cd backend"
    - "dotnet restore"

build:
    stage: build
    script:
        - "docker build -t LandscapeRegistryBackend -f .\LandscapeRegistry\Dockerfile ."

test:
    stage: test
    script: 
        - "cd $test"
        - "dotnet test"