
CREATE TABLE public.layer_state
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    layer_id bigint NOT NULL,
    state public.anchorstate DEFAULT 'active'::public.anchorstate NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT layer_state_pkey PRIMARY KEY (id)
);

ALTER TABLE ONLY public.layer_state
    ADD CONSTRAINT f_layer_state FOREIGN KEY (layer_id) REFERENCES public.layer(id) ON UPDATE CASCADE ON DELETE CASCADE;
