CREATE TABLE public.layer_color
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    color int NOT NULL,
    layer_id bigint NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    CONSTRAINT layer_color_pkey PRIMARY KEY (id)
);

ALTER TABLE ONLY public.layer_color
    ADD CONSTRAINT f_layer FOREIGN KEY (layer_id) REFERENCES public.layer(id) ON UPDATE CASCADE ON DELETE CASCADE;
    