CREATE TABLE public.layer_generators
(
    id bigint NOT NULL GENERATED ALWAYS AS IDENTITY,
    generators text[] NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    layer_id text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT layer_generators_pkey PRIMARY KEY (id),
    CONSTRAINT f_layer FOREIGN KEY (layer_id)
        REFERENCES public.layer (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
);
