name: call-frontend-package-variants

on:
  workflow_dispatch:
    inputs:
      baseVersion:
        description: 'Version of Base Image and Repository Tag; example: 0.14.80'
        required: true

jobs:
  call-frontend-package-variant-tsa:
    runs-on: ubuntu-20.04
    steps:
    - name: Set env variables
      run: |
        echo "variantName=tsa" >> $GITHUB_ENV
        echo "baseVersion=${{ github.event.inputs.baseVersion }}" >> $GITHUB_ENV
        echo "pluginsFrontend=@max-bytes/okplugin-generic-json-ingest@${{ github.event.inputs.baseVersion }} @max-bytes/okplugin-visualization@${{ github.event.inputs.baseVersion }}" >> $GITHUB_ENV
    - name: "Invoke frontend variant: TSA"
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: package-variants
        token: ${{ secrets.PAT }}
        inputs: '{ "variantName": "${{ env.variantName }}", "baseVersion": "${{ env.baseVersion }}", "pluginsFrontend": "${{ env.pluginsFrontend }}" }'
  call-frontend-package-variant-internal:
    runs-on: ubuntu-20.04
    steps:
    - name: Set env variables
      run: |
        echo "variantName=internal" >> $GITHUB_ENV
        echo "baseVersion=${{ github.event.inputs.baseVersion }}" >> $GITHUB_ENV
        echo "pluginsFrontend=@max-bytes/okplugin-generic-json-ingest@${{ github.event.inputs.baseVersion }} @max-bytes/okplugin-visualization@${{ github.event.inputs.baseVersion }}" >> $GITHUB_ENV
    - name: "Invoke frontend variant: internal"
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: package-variants
        token: ${{ secrets.PAT }}
        inputs: '{ "variantName": "${{ env.variantName }}", "baseVersion": "${{ env.baseVersion }}", "pluginsFrontend": "${{ env.pluginsFrontend }}" }'