name: call-package-variants

on:
  workflow_dispatch:
    inputs:
      baseVersion:
        description: 'Version of Base Image and Repository Tag; example: 0.14.80'
        required: true

jobs:
  call-package-variants:
    runs-on: ubuntu-20.04
    steps:
    - name: "Invoke variant: internal"
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: package-variants
        token: ${{ secrets.GITHUB_TOKEN }}
        inputs: '{ "variantName": "internal", "baseVersion": "${{ github.event.inputs.baseVersion }}", "pluginsBackend": "OKPluginGenericJSONIngest:${{ github.event.inputs.baseVersion }};OKPluginActiveDirectoryXMLIngest:${{ github.event.inputs.baseVersion }};OKPluginAnsibleInventoryScanIngest:${{ github.event.inputs.baseVersion }};OKPluginOIAKeycloak:${{ github.event.inputs.baseVersion }};OKPluginOIAOmnikeeper:${{ github.event.inputs.baseVersion }};OKPluginOIASharepoint:${{ github.event.inputs.baseVersion }};", "pluginsFrontend": "@max-bytes/okplugin-generic-json-ingest@${{ github.event.inputs.baseVersion }}" }'
