---
name: run-perf-tests

on: 
  workflow_dispatch:

jobs:
  tests:
    name: Run backend performance tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: omnikeeper_tests
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Run performance tests
        env:
          ConnectionStrings__DatabaseConnection: Server=localhost;Port=5432;User Id=postgres;Password=postgres;Database=omnikeeper_tests;Pooling=false
        run: |
          cd backend
          dotnet run --project ./PerfTests -c Release -- --job short --runtimes net6.0 --filter '*' --exporters json --strategy Monitoring
      - name: upload GetMergedAttributes benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark
          tool: 'benchmarkdotnet'
          output-file-path: backend/BenchmarkDotNet.Artifacts/results/PerfTests.GetMergedAttributesTest-report-full-compressed.json
          github-token: ${{ secrets.BENCHMARK_RESULTS_DEPLOY_TOKEN }}
          gh-pages-branch: main
          auto-push: true
          benchmark-data-dir-path: .
          alert-threshold: '150%'
          comment-on-alert: true
          fail-on-alert: true
          gh-repository: 'github.com/max-bytes/omnikeeper-benchmarks'
      - name: Remove File # HACK: otherwise, second call fails
        uses: JesseTG/rm@v1.0.3
        with:
          path: ./benchmark-data-repository
      - name: upload BulkReplaceAttributes benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark
          tool: 'benchmarkdotnet'
          output-file-path: backend/BenchmarkDotNet.Artifacts/results/PerfTests.BulkReplaceAttributesTest-report-full-compressed.json
          github-token: ${{ secrets.BENCHMARK_RESULTS_DEPLOY_TOKEN }}
          gh-pages-branch: main
          auto-push: true
          benchmark-data-dir-path: .
          alert-threshold: '150%'
          comment-on-alert: true
          fail-on-alert: true
          gh-repository: 'github.com/max-bytes/omnikeeper-benchmarks'
