---
name: run-perf-tests

on: 
  workflow_dispatch: # TODO: related issue: https://github.com/rhysd/github-action-benchmark/issues/73
  #push:
  #  branches:
  #    - master

jobs:
  tests:
    name: Run backend performance tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: omnikeeper_tests
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v1S
        with:
          dotnet-version: '6.0.x'
      - name: Run performance tests
        env:
          ConnectionStrings__DatabaseConnection: Server=localhost;Port=5432;User Id=postgres;Password=postgres;Database=omnikeeper_tests;Pooling=false
        run: |
          cd backend
          # dotnet nuget update source "Github nuget Repository" --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text
          dotnet run --project ./PerfTests -c Release -- --job short --runtimes net6.0 --filter PerfTests.GetMergedAttributesTest.GetMergedAttributes --exporters json --strategy Monitoring --iterationCount 50
      - name: Store benchmark result
        uses: rhysd/github-action-benchmark@v1
        with:
            tool: 'benchmarkdotnet'
            output-file-path: backend/BenchmarkDotNet.Artifacts/results/PerfTests.GetMergedAttributesTest-report-full-compressed.json
            gh-pages-branch: master # TODO: related issue: https://github.com/rhysd/github-action-benchmark/issues/51
            github-token: ${{ secrets.GITHUB_TOKEN }}
            auto-push: true
            benchmark-data-dir-path: docs/benchmarks
            alert-threshold: '150%'
            comment-on-alert: true
            fail-on-alert: true

