---
name: run-perf-tests

on: 
  #workflow_dispatch: # TODO: related issue: https://github.com/rhysd/github-action-benchmark/issues/73
  push:
    branches:
      - master

jobs:
  tests:
    name: Run backend performance tests
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: omnikeeper_tests
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Run performance tests
        env:
          ConnectionStrings__DatabaseConnection: Server=localhost;Port=5432;User Id=postgres;Password=postgres;Database=omnikeeper_tests;Pooling=false
        run: |
          cd backend
          dotnet nuget update source "Github nuget Repository" --username "${{ github.actor }}" --password "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text
          dotnet run --project ./PerfTests -c Release -- --job short --runtimes netcoreapp31 --filter *SearchForMergedCIsByTraits* --exporters json
      - name: Store benchmark result
        uses: Happypig375/github-action-benchmark@v1
        with:
            tool: 'benchmarkdotnet'
            output-file-path: backend/BenchmarkDotNet.Artifacts/results/PerfTests.SearchForMergedCIsByTraitsTest-report-full-compressed.json
            gh-pages-branch: master
            benchmark-data-dir-path: docs/benchmarks

