name: update-wiki

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'docs/**'

jobs:
  update-wiki:
    runs-on: ubuntu-20.04
    env:
      VARIANT_NAME: ${{ github.event.inputs.variantName }}
      BASE_VERSION: ${{ github.event.inputs.baseVersion }}
      PLUGINS_BACKEND: ${{ github.event.inputs.pluginsBackend }}
    steps:
      - name: Checkout base code
        uses: actions/checkout@v2
        with:
          path: base
      - name: Checkout wiki code
        uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - uses: rlespinasse/drawio-export-action@v1.x
        with:
          path: base/docs/source
          format: svg
          output: .
          remove-page-suffix: true
      - name: Push to wiki
        run: |
          find wiki/* ! -name '.git' -exec rm -rf {} +
          cp -a base/docs/source/. wiki/
          cd wiki
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Updates" && git push
